version: '3'
services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  app:
    image: receipt_processor
    ports:
      - "5002:5000"
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis